### ISSUE TITLE
react should be a peer dependency in package.json in order to use npm

### ISSUE THREAD

**Issue by Tony1023** [arnaudambro/react-swipe-to-delete-ios#13]
Using `npm install` to install this package in an existing React project results in a duplicate React error, discoverable by `npm ls react`. As per the [react site](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react), react should be declared as a peer dependency.

Although `npm` is not suggested as a package manager to use for this package, it's still good to point out this because the problem basically makes this package unusable by existing projects with `npm`.

**Comment by arnaudambro** [comment]
done in the last version 1.0.10, thanks !
