### ISSUE TITLE
[chore] Changing peer dependencies that currently prevent any use with react 17

### ISSUE THREAD

**Issue by korbav** [arnaudambro/react-swipe-to-delete-ios#16]
The current peer dependencies are set this way : 

```
"peerDependencies": {
        "prop-types": "^15.7.2",
        "react": "^16.13.0",
        "react-dom": "^16.13.0",
        "react-scripts": "^3.4.0"
 }
```
      
Do we have any reason to not be more permissive ?
It's currently preventing projects to update themselves with libraries that require react-scripts & react to be greater versions.
If there's no blocker, I would suggest something like : 
      
```
"peerDependencies": {
    "prop-types": "^15.7.2",
    "react": "^16.13.0 || ^17.0.0",
    "react-dom": "^16.13.0 || ^17.0.0",
    "react-scripts": "^3.4.0 || ^4.0.0"
}
```

**Comment by arnaudambro** [comment]
done in v2.0.3
