### ISSUE TITLE
swipe both ways

### ISSUE THREAD

**Issue by mhezzet** [arnaudambro/react-swipe-to-delete-ios#2]
hi man thanks for the component, but can u make it swipe both ways

**Comment by arnaudambro** [comment]
Sorry didn't see your message
I can do it when I have time, but you can maybe have a look and propose a PR if you wish

**Comment by korbav** [comment]
@arnaudambro PR created here [https://github.com/arnaudambro/react-swipe-to-delete-ios/pull/11](https://github.com/arnaudambro/react-swipe-to-delete-ios/pull/11)
